[project]
name = "web-recalqula-v2"
version = "1.0.0"
description = "Calculadora para projetos de recalque"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "django>=5.2.3",
  "django-cors-headers>=4.7.0",
  "djangorestframework>=3.16.0",
]
